apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: unicorn-front-replica-set
  labels:
    app: unicorn-front-set
spec:
  template:
    metadata:
      name: unicorn-front-pod
      labels:
        app: unicorn-front-set
    spec:
      containers:
      - name: unicorn-front
        image: registry.takima.io/school/proxy/nginx
  replicas: 3
  selector:
    matchLabels:
      app: unicorn-front-set
