# Default values for CDB app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# We have only done front for now

api:
  ingress:
    tlsEnabled: false
    host: api.jpouradierduteil.takihq.takima.school
  replicaCount: 1
  image:
    repository: registry.gitlab.com/takima-school/images/cdb/api
    tag: latest

front:
  enabled: true
  image:
    repository: registry.gitlab.com/takima-school/images/cdb/www
    tag: latest
  replicaCount: 1
  ingress:
    tlsEnabled: false
    host: www.jpouradierduteil.takihq.takima.school

db:
  replicas: 1
pgadmin:
  enabled: false
  email: "admin@takima.io"
  password: "YWRtaW4xMjMq" #base64 of admin123*