# Default values for CDB app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# We have only done front for now
name: cdb

api:
  ingress:
    tlsEnabled: true
    host: api.jpouradierduteil.takihq.takima.school
  replicaCount: 2
  image:
    repository: registry.gitlab.com/takima-school/images/cdb/api
    tag: latest

front:
  enabled: true
  image:
    repository: registry.gitlab.com/takima-school/images/cdb/www
    tag: latest
  replicaCount: 2
  ingress:
    tlsEnabled: true
    host: www.jpouradierduteil.takihq.takima.school

pgadmin:
  enabled: true
  email: "admin@takima.io"
  password: "YWRtaW4xMjMq" #base64 of admin123*