{{- if .Values.front.enabled }}  
  {{- $apiUrl := "" }}  
  {{- if .Values.api.ingress.tlsEnabled }}  
    {{- $apiUrl = printf "https://%s-%s" .Values.name .Values.api.ingress.host | quote }}
  {{- else }}  
    {{- $apiUrl = printf "http://%s-%s" .Values.name .Values.api.ingress.host | quote }}
  {{- end }}  
apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: {{.Values.name}}-front-config
data:  
  API_URL: {{ $apiUrl }}
{{- end }}