{{- if .Values.front.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{.Release.Name}}-front-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "{{.Release.Name}}-{{ .Values.front.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: {{.Release.Name}}-front-service
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- if .Values.front.ingress.tlsEnabled }}
  tls:
  - hosts:
    - "{{.Release.Name}}-{{ .Values.front.ingress.host }}"
    secretName: app-wildcard
  {{- end }}
{{- end }}
