{{- if .Values.front.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-front-service
spec:
  selector:
    app: front-{{.Values.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}