apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-api
spec:
  ingressClassName: nginx
  rules:
    - host: "{{.Release.Name}}-{{ .Values.api.ingress.host }}"
      http:
        paths:
          - backend:
              service:
                name: {{.Release.Name}}-api-service
                port:
                  number: 80
            path: /
            pathType: Prefix
       {{- if .Values.api.ingress.tlsEnabled }}
  tls:
    - hosts:
      - "{{.Release.Name}}-{{ .Values.api.ingress.host }}"
      secretName: app-wildcard

  {{- end}}