apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{.Release.Name}}-api-deploy
  labels:
    app: api-{{.Chart.AppVersion}}
    access: db
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: api-{{.Release.Name}}
        access: db
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: api-{{.Release.Name}}
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: DB_ENDPOINT
          value: {{.Release.Name}}-db:5432
        - name: POSTGRES_DB
          value: {{.Release.Name}}
        - name: POSTGRES_USER
          valueFrom:
           secretKeyRef:
              name: {{.Release.Name}}.{{.Release.Name}}-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}.{{.Release.Name}}-db.credentials.postgresql.acid.zalan.do
              key: password
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: takima-school-registry
